### ISSUE TITLE
OAI output format questions

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/fcrepo4-oaiprovider#30] opened 2018-02-09 23:12 UTC
1. `?verb=Identify`
* [x]  oai-id:sampleIdentifier - is the sample URL ok (`oai:era.library.ualberta.ca:1/b8515q959`) or should the UUID applied via the migration be used?

2. Record header
* [x] `record/header/identifier`: should the format be retained e.g., oai:era.library.ualberta.ca:1/0464db01-e31a-42af-922a-03d69ddd1735?
* [x] `record/header/setSpec`: OAI sets leverages the `ual:path` property to yield simpler JCR queries - is this ok (e.g., 1272a36b-cca5-41bb-9cf0-9bc3fb658c07/811624cc-93c0-466d-b133-1603c4375f89) ? 

3. ETDMS - `?verb=ListRecords&metadataPrefix=oai_etdms`
* [x] `etd_ms:type` OAI property populated from the original Fedora Objects `rdf:type` (as per [metadata spec](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/Jupiter%20OAI%20mapping.xlsx)) which look like the following, is this ok? Or should a URI hard-coded of objects with the IRThesis model to the `bibo:Thesis` URI?
```
<dc:type>http://fedora.info/definitions/v4/repository#Container</dc:type>
<dc:type>http://fedora.info/definitions/v4/repository#Resource</dc:type>
<dc:type>http://purl.org/ontology/bibo/Thesis</dc:type>
<dc:type>http://pcdm.org/models#Object</dc:type>
```

4. General
* [x] Double-check `dc:rights` for html elements and how the different metadata types render
* [x] Double-check `dc:date`

Screenshot demonstrating some of the above

![oai_screenshot](https://user-images.githubusercontent.com/879785/36105940-19e8ecf8-0fd3-11e8-8f70-fd4e7b279416.png)

**Comment by anayram** [comment] 2018-05-08 14:41
Follow up on conversation about setSpec:

setSpecs:
> a colon [:] separated list indicating the path from the root of the set hierarchy to the respective node.
From: [https://www.openarchives.org/OAI/openarchivesprotocol.html#Set](https://www.openarchives.org/OAI/openarchivesprotocol.html#Set)

Look into replacing ' / ' for ' : ' as separator for set path.

**Comment by anayram** [comment] 2018-05-08 14:48
Revision: 
currently `setSpec` contains path to fedora object in the form of `setuuid/objectuuid`

OAI specifications suggest that only the set identifier needs to be output in setSpec, so we can drop the second uuid for the fedora object altogether. See: https://www.openarchives.org/OAI/openarchivesprotocol.html#Set

**Comment by anayram** [comment] 2018-05-23 19:50
Here are quick answers to the four parts of the original issue. @jefferya please let me know if there is anything I missed or that needs to be clarified.

1. OAI identifiers
Because we are moving away from noids we should probably use UUIDs but I'll let @sfarnel @pbinkley @weiweishi or others to weigh in

~~2. Record header
For `setSpec` drop object UUID and use only set UUID (see comments above).~~

3. ETDMS
For ETDMS type see [https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/33](https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/33)

4. General
Rights and dates metadata to be checked once we have OAI service available.

**Comment by jefferya** [comment] 2018-05-23 22:59
Though I added the following yesterday but it never saved.
 
I'd like to add the following comment to the conversation (sorry for the delay as my time with CWRC was hectic preparing for a workshop and upcoming conference) regarding the setSpec.
 
A bit more detail on the `ListSets` verb response from the current OAI Provider - the `setSpec` value is the ual:path property  comprised of the `community UUID` / `collection UUID` which aligns with the `setName` comprised of the `community label` / `collection label`. The manner in which the ual:path is attached to the object makes both displaying a value easy and implementing the selection JCR-SQL2 query within Modeshape to restrict the results of a ListRecords or ListIdentifiers OAI request that limits results by setSpec.

A quick update, I've yet to discover the JCR-SQL2 query to work with just the collection and not the community/collection pair.

**Comment by anayram** [comment] 2018-05-31 18:46
All good with `setSpec`, we can keep the community:collection pair separated by `:`

?verb=Identify
@jefferya I believe you are already working on this but we need to remove the preceding 1/ before UUID in OAI identifiers. This may need just a single change but in case not, here are some elements that use oai ids:
`oai-id:sampleIdentifier`
`OAI-PMH:record/header/identifier`
`atom:link`
and any other elements containing oai identifiers.

This ticket can be closed once the above changes are confirmed.

**Comment by anayram** [comment] 2018-06-19 19:29
All changes done. Closing issue.

**Closed as completed by anayram** 2018-06-19 19:29 UTC
Labels: metadata
